apiVersion: v1
kind: Service
metadata:
  name: fsl
  namespace: production
spec:
  ports:
  - port: 8080
    targetPort: 3000
    nodePort: 30080
    name: web
  type: NodePort
  selector:
    app: fsl